# Generated by Django 5.0.4 on 2025-06-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('preparacion', 'En preparación'), ('listo', 'Listo para retiro/entrega'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
