# Generated by Django 5.0.4 on 2025-06-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_compra_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
